#!/bin/bash

# ----------------------- setup -----------------------
ACCESS_TOKEN=$(git config asana.token)
WORKSPACE=$(git config asana.workspace)
TEAM=$(git config asana.team)
ASANA_USER=$(git config asana.user)
MY_PROJECT=$(git config asana.my.weekly)
WEEKLY_NAME="Platform-Sprint-"$(date -dlast-monday +%Y-%m-%d)
# echo $WEEKLY_NAME

# ----------------------- create weekly project, if needed -----------------------
# check if the sprint project exists. if not, create it
EXISTS=$(curl \
  -H "Authorization: Bearer ${ACCESS_TOKEN}" \
  -sX GET "https://app.asana.com/api/1.0/projects?workspace=${WORKSPACE}&team=${TEAM}" \
  | json_pp | grep ${WEEKLY_NAME} 2>&1
)
if [ -z "$EXISTS" ]; then
  # echo "need to create"
  curl \
    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
    -H "Content-type: application/json" \
    -sX POST "https://app.asana.com/api/1.0/projects" \
    -d "{\"data\":{\"name\":\"${WEEKLY_NAME}\",\"public\":true,\"workspace\":\"${WORKSPACE}\",\"team\":\"${TEAM}\"}}" \
    > /dev/null 2>&1
fi

# ----------------------- select weekly project -----------------------
# use the weekly project id
PLATFORM_PROJECT=$(curl \
  -H "Authorization: Bearer ${ACCESS_TOKEN}" \
  -sX GET "https://app.asana.com/api/1.0/projects?workspace=${WORKSPACE}&team=${TEAM}" \
    | json_pp | grep ${WEEKLY_NAME} -a1 -b1 | grep '"id"' \
    | sed 's/.*"id" : \([[:digit:]]\+\),\?/\1/g'
)
#echo $PLATFORM_PROJECT

# ----------------------- create asana task -----------------------
# Find repository host
for repository in $(git remote -v | awk '{ print $2 }'); do
    scheme="$(echo $repository | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    url="$(echo ${repository/$scheme/})"
    user="$(echo $url | grep @ | cut -d@ -f1)"
    if [[ $scheme == "" ]]; then
        host="$(echo ${url/$user@/} | cut -d: -f1)"
        path="$(echo $url | grep : | cut -d: -f2-)"
    else
        host="$(echo ${url/$user@/} | cut -d/ -f1)"
        path="$(echo $url | grep / | cut -d/ -f2-)"
    fi
    project="$(echo ${path%.*})"

    # Bitbucket or GitHub
    if [[ $host == "bitbucket.org" ]]; then
        commit_url="https://bitbucket.org/$project/commits/"
        break;
    elif [[ $host == "github.com" ]]; then
        commit_url="https://github.com/$project/commit/"
        break;
    else
        commit_url=""
    fi
done
URL="$commit_url"$(git rev-parse HEAD)
# URL="https://test"

# use commit message as task title & note
MESSAGE=$(git log -1 --pretty=%B | head -1)
# echo "$MESSAGE"
NOTES=$(git log -1 --pretty=%b | sed ':a;N;$!ba;s/\n/\\n/g')
# echo $NOTES

# echo ""
# echo "{\"data\":{\"completed\":true,\"assignee\":\"${ASANA_USER}\",\"name\":\"${MESSAGE}\",\"notes\":""${NOTES}"", \"workspace\":\"${WORKSPACE}\",\"projects\":[109718621833982,142940733164636]}}"

# make a task on Asana
curl \
  -H "Authorization: Bearer ${ACCESS_TOKEN}" \
  -H "Content-type: application/json" \
  -sX POST "https://app.asana.com/api/1.0/tasks" \
  -d "{\"data\":{\"completed\":true, \"assignee\":\"${ASANA_USER}\", \"name\":\"${MESSAGE}\",\"notes\":\"${URL}\\n\\n${NOTES}\", \"workspace\":\"${WORKSPACE}\",\"projects\":[$MY_PROJECT,$PLATFORM_PROJECT]}}" \
  > /dev/null 2>&1
