#!/bin/bash
. setup_functions

############################# Qualcomm Atheros Ethernet #############################
# if the motherboard is using this (which is not recognized by Ubuntu right away)
# sudo apt-get install git dkms build-essential linux-headers-generic
# sudo dkms add ./atheros_ethernet
# sudo dkms build atheros_ethernet/2.0
# sudo dkms install atheros_ethernet/2.0

pause "Select a fast, local mirror, then press [Enter]..."

# # update apt repos
# sudo apt-get update

############################# setup workstation #############################

# essential
pause "Instaling essential packages. Press [Enter] to continue..."

install_linux apt git
install_linux apt mercurial
install_linux apt curl
install_linux apt vim
install_linux apt python-software-properties
install_linux apt python-pip
install_linux apt python3-pip
install_linux apt openssh-server
install_linux apt gitk
install_linux apt tmux
install_linux apt xclip
install_linux apt logkeys

# browsers
install_linux apt libindicator7
install_linux apt libappindicator1
install_linux deb google-chrome-stable "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

# sublime
install_linux deb sublime "https://download.sublimetext.com/sublime-text_build-3126_amd64.deb"

############################# customize tools #############################

pause "Configuring tools & scripts. Press [Enter] to continue..."

# bash config
git clone https://github.com/exklamationmark/dotfiles.git /tmp/dotfiles
cp -f /tmp/dotfiles/.bashrc ~/.bashrc
cp -f /tmp/dotfiles/.bash_aliases ~/.bash_aliases

# add xclip helper functions
cat /tmp/dotfiles/.bash_xclip >> ~/.bash_aliases

# define a custom prompt that shows more info on git repository
cat /tmp/dotfiles/.bash_custom_prompt >> ~/.bashrc
# golang env variables
cp -f /tmp/dotfiles/.bash_golang ~/.bash_golang

# customize vim
# vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# minimum .vimrc
cp -f /tmp/dotfiles/.vimrc.vundle ~/.vimrc # basic vundle only
# install solarized color theme
vim +'PluginInstall altercation/vim-colors-solarized' +qall
# install golang plugin for vim
vim +'PluginInstall fatih/vim-go' +qall
# install dockerfile plugin for vim
vim +'PluginInstall ekalinin/Dockerfile.vim' +qall
# minimum .vimrc
cp -f /tmp/dotfiles/.vimrc ~/.vimrc # vundle + plugins + settings
# use solarized gnome (terminal)
git clone https://github.com/Anthony25/gnome-terminal-colors-solarized.git /tmp/gnome-terminal-colors-solarized
/tmp/gnome-terminal-colors-solarized/set_dark.sh

# tmux config
cp /tmp/dotfiles/.tmux.conf ~/.tmux.conf

# git config
cp -f /tmp/dotfiles/.gitconfig ~/.gitconfig

# coding environment
if [[ -d "~/workspace" ]]
then
	mkdir -p ~/workspace
fi

echo -e $COLOR_BLUE"Run "$COLOR_RED"source ~/.bashrc"$COLOR_NONE" then run "$COLOR_RED"./workstuff"$COLOR_NONE
