#!/bin/bash

# coloring helper
COLOR_RED='\e[0;31m'
COLOR_GREEN='\e[0;32m'
COLOR_YELLOW='\e[0;33m'
COLOR_BLUE='\e[0;34m'
COLOR_MAGENTA='\e[0;35m'
COLOR_NONE='\e[0m'

# package status helper
is_installed(){
	if dpkg --get-selections | grep -q "^$1[[:space:]]*install$" >/dev/null
	then
		return 0
	fi
	return 1
}
# instalation helper
install_apt() {
	sudo apt-get install $1
}
install_deb() {
	local PKG=$1
	local PACKAGE_URL=$2

	if [[ -n "$PACKAGE_URL" ]]
	then
		curl $PACKAGE_URL > ~/.temp/$PKG.deb
	fi
	sudo dpkg -i ~/.temp/$PKG.deb
}
install() {
	local PKG=$1
	local INSTALLER=$2
	if is_installed $PKG
	then
		echo -e $COLOR_GREEN"$PKG is already installed"$COLOR_NONE
		return 0
	fi

	# run apt-get install for apt packages
	if ( ! is_installed $PKG ) && [[ $INSTALLER == "apt" ]]
	then
		echo -e $COLOR_YELLOW"Installing $PKG using $INSTALLER ..."$COLOR_NONE
		install_apt $PKG
	fi

	# run dpkg -i for .deb files
	if ( ! is_installed $PKG ) && [[ $INSTALLER == "deb" ]]
	then
		local PACKAGE_URL=$3
		echo -e $COLOR_YELLOW"Installing $PKG using $INSTALLER ..."$COLOR_NONE
		install_deb $PKG $PACKAGE_URL
	fi
}
