#!/bin/bash

# coloring helper
GNOME_COLOR_RED='\e[0;31m'
GNOME_GNOME_COLOR_GREEN='\e[0;32m'
GNOME_COLOR_YELLOW='\e[0;33m'
GNOME_COLOR_BLUE='\e[0;34m'
GNOME_COLOR_NONE='\e[0m'
# OSX colors
OSX_COLOR_RED='\033[0;31m'
OSX_COLOR_GREEN='\033[0;32m'
OSX_COLOR_YELLOW='\033[0;33m'
OSX_COLOR_BLUE='\033[0;34m'
OSX_COLOR_NONE='\033[0m'

# package status helper
is_installed_dpkg(){
  local PACKAGE=$1
  if dpkg --get-selections | grep -q "^$PACKAGE[[:space:]]*install$" >/dev/null
  then
    return 0
  fi
  return 1
}
# instalation helper
install_apt() {
  local PACKAGE=$1
  sudo apt-get install $PACKAGE -y
}
install_deb() {
  local PACKAGE=$1
  local URL=$2

  if [[ -n "$URL" ]]
  then
    curl $URL > ~/.temp/$PACKAGE.deb
  fi
  sudo dpkg -i ~/.temp/$PACKAGE.deb
}
install_dmg(){
  local NAME=$1
  local URL=$2
  local DIR=$3
  
  curl -o $DIR/$NAME.dmg $URL
  # mount dmg
  sudo hdiutil attach $TEMPDIR/$NAME.dmg
  # install
  sudo installer -pkg /Volumes/$NAME/$NAME.pkg -target /
  # unmount dmg
  sudo hdiutil detach /Volumes/$NAME
}
install_linux() {
  local PKG=$1
  local INSTALLER=$2
  if is_installed_dpkg $PKG
  then
    echo -e $GNOME_GNOME_COLOR_GREEN"$PKG is already installed"$GNOME_COLOR_NONE
    return 0
  fi

  # run apt-get install for apt packages
  if ( ! is_installed_dpkg $PKG ) && [[ $INSTALLER == "apt" ]]
  then
    echo -e $GNOME_COLOR_YELLOW"Installing $PKG using $INSTALLER ..."$GNOME_COLOR_NONE
    install_apt $PKG
  fi

  # run dpkg -i for .deb files
  if ( ! is_installed_dpkg $PKG ) && [[ $INSTALLER == "deb" ]]
  then
    local PACKAGE_URL=$3
    echo -e $GNOME_COLOR_YELLOW"Installing $PKG using $INSTALLER ..."$GNOME_COLOR_NONE
    install_deb $PKG $PACKAGE_URL
  fi
}
