#!/bin/bash
set -exuo

source lib/install.bash
source lib/configure.bash

configure_apt_mirror
sudo apt-get update



#################### Day-to-day essentials ####################
echo "Installing must-have packages..."

install apt make
install apt curl
install apt git
install apt neovim # TODO(mark): apt-get remove vim
install apt gitk
install apt tmux
install apt xclip
install apt w3m
install apt pandoc
install apt i3
install apt tree
install apt jq



#################### /etc/bash.bashrc for Ubuntu 20.04 ####################
ln -sf ${PWD}/data/.bashrc ~/.bashrc



#################### Workspace for code ####################
if [ ! -d "~/workspace/src" ]
then
	mkdir -p ~/workspace/src
fi



#################### Custom envs ####################
# tmux
ln -sf ${PWD}/data/.tmux.conf ~/.tmux.conf
# git
render_gitconfig
ln -sf ${PWD}/data/.gitconfig ~/.gitconfig
echo "if [ -f /etc/bash_completion.d/git-completion.bash ]; then
	. /etc/bash_completion.d/git-completion.bash;
fi" >> ~/.bashrc

# i3
mkdir -p ~/.i3
ln -sf ${PWD}/data/.i3.config ~/.i3/config

# inputrc
ln -sf ${PWD}/data/.inputrc ~/.inputrc
# w3m
ln -sf  ${PWD}/data/.w3m ~/



#################### Bash ####################
echo "# customized bash" >> ~/.bashrc

ln -sf ${PWD}/data/.bash_extra ~/.bash_extra
echo "if [ -f ~/.bash_extra ]; then
    . ~/.bash_extra
fi" >> ~/.bashrc

ln -sf ${PWD}/data/.bash_aliases ~/.bash_aliases
echo "if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi" >> ~/.bashrc

ln -sf ${PWD}/data/.bash_custom_prompt ~/.bash_custom_prompt
echo "if [ -f ~/.bash_custom_prompt ]; then
    . ~/.bash_custom_prompt
fi" >> ~/.bashrc



#################### Bash ####################
# vundle
# git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# minimum .vimrc to bootstrap
# cp -f ./data/.vimrc.vundle ~/.vimrc # basic vundle only

# install solarized color theme
# vim +'PluginInstall altercation/vim-colors-solarized' +qall
# install golang plugin for vim
# vim +'PluginInstall fatih/vim-go' +qall
# install dockerfile plugin for vim
# vim +'PluginInstall ekalinin/Dockerfile.vim' +qall

# .vimrc with frequently-used bindings
# cp -f ./data/.vimrc ~/.vimrc # vundle + plugins + settings

# NeoVim
mkdir -p ~/.config/nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
ln -sf ${PWD}/data/.neovim.init.vim ~/.config/nvim/init.vim
nvim +':PlugInstall' +qall

# Connect got github.com for the first time
connect_to_github





#################### Some system tuning ####################
# disable automatic apt update
sudo systemctl disable apt-daily-upgrade.service
sudo systemctl disable apt-daily-upgrade.timer
sudo systemctl disable apt-daily.service
sudo systemctl disable apt-daily.timer
# disable animation
gsettings set org.gnome.desktop.interface enable-animations false
# TODO: set terminal profile to use: Solarized
# TODO: set temrinal font size


#################### Cleanup ####################
echo -e $BLUE"Edit "$RED"/etc/hosts"$NONE" and add your hostname"$NONE
echo -e $BLUE"Run "$RED"source ~/.bashrc"$NONE" then run "$RED"./workstuff"$NONE
