#! /bin/bash

# get passpharse
echo "Enter passphrase to decrypt network info:"
read -s PASSPHRASE

FILES=$(sudo ls ./network_connections/)
for file in $FILES
do
  # echo "echo $PASSPHRASE | gpg --passphrase-fd 0 --out ./network_connections/$file.decrypted --decrypt ./network_connections/$file"
  echo $PASSPHRASE | gpg --passphrase-fd 0 --out ./network_connections/$file.decrypted --decrypt ./network_connections/$file
done
