#!/bin/bash
. setup_functions

# temp folder
rm -rf ~/.temp
mkdir -p ~/.temp




# advisable to first select a faster mirror

# essential 
install_linux git apt
install_linux curl apt
install_linux vim apt
install_linux python-software-properties apt

# browsers
install_linux libxss1:amd64 apt
install_linux google-chrome-stable deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

# version control
install_linux gitk apt
install_linux kdiff3 apt

# bash config
git clone https://github.com/exklamationmark/dotfiles.git ~/.temp/dotfiles
cp -f ~/.temp/dotfiles/.bashrc ~/.bashrc
cp -f ~/.temp/dotfiles/.bash_aliases ~/.bash_aliases
source ~/.bashrc

# git config
cp -f ~/.temp/dotfiles/.gitconfig ~/.gitconfig

# show branch name in git repo
cat ~/.temp/dotfiles/.custom_prompt >> ~/.bashrc

# git alias
echo "alias gitka='gitk --all'" >> ~/.bash_aliases

# minimum .vimrc
cp -f ~/.temp/dotfiles/.vimrc ~/.vimrc

# vim's plugin: pathogen
rm -rf ~/.vim
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -Sso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
echo "\n# Pathogen\nexecute pathogen#infect()" >> ~/.vimrc

# use solarized theme in vim
git clone git://github.com/altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized
echo "\n Solarized\nset background=dark\ncolorscheme solarized" >> ~/.vimrc
echo "export TERM=screen-256color" >> ~/.bashrc

# user solarized gnome (terminal) 
git clone git://github.com/sigurdga/gnome-terminal-colors-solarized.git ~/.temp/gnome-terminal-colors-solarized
sh ~/.temp/gnome-terminal-colors-solarized/set_dark.sh

# tmux
install_linux tmux apt

# coding environment
if [[ -d "~/workspace" ]]
then
	mkdir ~/workspace
fi

#--------------------------------------------------------------------------------------------------
# go
install_linux golang apt
# gopath
echo "export GOPATH='$HOME/workspace'" >> ~/.bashrc
echo "export PATH=\$PATH:\$GOPATH/bin" >> ~/.bashrc
mkdir -p ~/workspace/bin
mkdir -p ~/workspace/pkg
mkdir -p ~/workspace/src
source ~/.bashrc
# syntax highlighting in vim
git clone git://github.com/jnwhiteh/vim-golang.git ~/.vim/bundle/vim-golang
mkdir -p $HOME/.vim/ftdetect
mkdir -p $HOME/.vim/syntax
mkdir -p $HOME/.vim/autoload/go
ln -s $HOME/.vim/bundle/vim-golang/ftdetect/gofiletype.vim $HOME/.vim/ftdetect/
ln -s $HOME/.vim/bundle/vim-golang/syntax/go.vim $HOME/.vim/syntax
ln -s $HOME/.vim/bundle/vim-golang/autoload/go/complete.vim $HOME/.vim/autoload/go

# docker
sudo groupadd docker
USER=`whoami`
install_linux docker.io apt
sudo usermod -aG docker $USER
sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
# syntax highlighting for docker files
git clone https://github.com/ekalinin/Dockerfile.vim.git ~/.vim/bundle/Dockerfile
# docker login
cp -f ~/.temp/dotfiles/.dockercfg ~/.dockercfg

# postgresql
install_linux postgresql-9.3 apt
install_linux postgresql-server-dev-9.3 apt

# redis
install_linux redis-server apt

# rabbitmq
install_linux rabbitmq-server apt
sudo rabbitmq-plugins enable rabbitmq_management
sudo service rabbitmq-server restart

# rvm with ruby
if [[ ! -d ~/.rvm ]]
then
	\curl -sSL https://get.rvm.io | bash -s stable --ruby
else
	echo -e $COLOR_GREEN"RVM is already installed"$COLOR_NONE
	echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc #since what RVM put there was lost when ubuntu_setup is run twice
	source ~/.bashrc
fi
# progress bar for gem download
echo progress-bar >> ~/.curlrc
echo "gem: --no-rdoc --no-ri " >> ~/.gemrc

# nodejs
apt-add-repository ppa:chris-lea/node.js
apt-get update
install_linux nodejs apt
npm config set prefix $HOME/npm
echo 'export PATH=$PATH:$HOME/npm/bin' >> ~/.bashrc
# misc.
# # Spotify
# sudo bash -c "echo '# Spotify' >> /etc/apt/sources.list"
# sudo bash -c "echo 'deb http://repository.spotify.com stable non-free' >> /etc/apt/sources.list"
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
# sudo apt-get update && sudo apt-get install spotify-client

# hipchat
sudo su
echo "deb http://downloads.hipchat.com/linux/apt stable main" > \
    /etc/apt/sources.list.d/atlassian-hipchat.list
wget -O - https://www.hipchat.com/keys/hipchat-linux.key | apt-key add -
apt-get update
apt-get install hipchat

# # xbindkeys mapping
# if hash xbindkeys 2>/dev/null; then echo "xbindkeys is installed\n"
# else echo "xbindkeys is not installed. installing..\n"
# 	sudo apt-get install xbindkeys
# fi
# git clone https://gist.github.com/5487103.git $folder/xbindkeysrc
# sudo mv $folder/xbindkeysrc/.xbindkeysrc ~/.xbindkeysrc






# clean up
rm -rf ~/.temp
# echo -e $COLOR_BLUE"To get things started correctly, you might wanna do "$COLOR_RED"source ~/.bashrc"$COLOR_NONE" or re-open all the terminals"
