#!/bin/bash
. setup_functions

############################# development things #############################

# ----------------------------- go (1.11.2) -----------------------------
echo -e $COLOR_BLUE"Install go 1.11.2"$COLOR_NONE
sudo rm -rf /usr/local/go
curl 'https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz' > /tmp/golang.tar.gz
sudo tar -C /usr/local/ -xzvf /tmp/golang.tar.gz
sudo ln -sf /usr/local/go/bin/go /usr/local/bin/go
# tool for dependency management
go get github.com/tools/godep
# linter
go get github.com/golang/lint/golint
# vim-go binaries
vim +'GoInstallBinaries' +qall

# ----------------------------- docker -----------------------------
# pre-requisites
install_linux apt apt-transport-https
install_linux apt ca-certificates
install_linux apt curl
install_linux apt software-properties-common

# add docker's GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# install
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
install_linux apt docker-ce

# add current user to docker group
USER=`whoami`
sudo usermod -aG docker $USER

# get systemd to load http-proxy config for docker
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo cp -f /tmp/dotfiles/docker-http-proxy.conf /etc/systemd/system/docker.service.d/http-proxy.conf
sudo systemctl deamon-reload
sudo systemctl restart docker

# ----------------------------- docker-compose -----------------------------
curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
chmod +x /tmp/docker-compose
sudo mv /tmp/docker-compose /usr/local/bin/docker-compose

# ############################# key mapping #############################
# install_linux apt gnome-tweak-tool
# # open it, make Caps Lock an additional control in the Typing section

############################# clean up #############################
echo -e $COLOR_BLUE"To get things started correctly, you might wanna do "$COLOR_RED"source ~/.bashrc"$COLOR_NONE" or start a new terminal session"
