# User Ctrl-a as tmux's prefix
set -g prefix C-a
unbind C-b

set -s escape-time 1

# Start indexing panes & window with 1, 2, 3...
set -g base-index 1
set -g pane-base-index 1

# Key-bindings
bind r source-file ~/.tmux.conf
bind C-a send-prefix                                          # send C-a down
bind | split-window -h
bind - split-window -v
# Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Move between windows
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
# Resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 8

# Status bar
# set -g status-justify centre
set -g visual-activity on

# History
set-option -g history-limit 10000
